services:
  dept-hour-booking:
    build:
      context: .
      dockerfile: Dockerfile
    image: depthourbooking-dept-hour-booking:latest
    environment:
      - DOCKER_CONTAINER=true
      - DEPT_CLIENT_ID=${DEPT_CLIENT_ID}
      - DEPT_CLIENT_SECRET=${DEPT_CLIENT_SECRET}
      - DEPT_GOOGLE_ID_TOKEN=${DEPT_GOOGLE_ID_TOKEN}
      - DEPT_EMPLOYEE_ID=${DEPT_EMPLOYEE_ID}
      - DEPT_CORPORATION_ID=${DEPT_CORPORATION_ID}
      - DEPT_DEFAULT_ACTIVITY_ID=${DEPT_DEFAULT_ACTIVITY_ID}
      - DEPT_DEFAULT_PROJECT_ID=${DEPT_DEFAULT_PROJECT_ID}
      - DEPT_DEFAULT_COMPANY_ID=${DEPT_DEFAULT_COMPANY_ID}
      - DEPT_DEFAULT_BUDGET_ID=${DEPT_DEFAULT_BUDGET_ID}
    stdin_open: true
    tty: false
